<!-- Doctype -->
<?php echo $this->doctype() . PHP_EOL ?>
<html>
    <head> 
        <!-- Titulo da Página -->
        <?php echo $this->headTitle() . PHP_EOL; ?>
        <!-- Meta -->
        <?php echo $this->headMeta() . PHP_EOL; ?>
        <!-- Css -->
        <?php
        echo $this->headLink()
                ->prependStylesheet($this->baseUrl() . '/styles/style.css')
                ->prependStylesheet($this->baseUrl() . '/styles/form.css') . PHP_EOL;
        ?>
    </head>
    
    <body>

        <div id="barrinha"></div>
        <div id="estrutura">


            <div id="topo">
                <h1>Vinhos Da Hora</h1>
                <h2>Sistema Administrativo</h2>
            </div>

            <div class="clearfix"></div>
            <!-- Menu Horizontal -->
            <div id="menu-horizontal">
                <?php echo $this->navigation()
                        ->menu()
                        ->setMaxDepth(0)
                        ->render(); ?>
            </div>

            <div class="clearfix"></div>


            <div id="content">
                <div id="breadcrumbs">
                    <h3>
                        <?php echo $this->navigation()
                                ->breadcrumbs()
                                ->setMinDepth(0)
                                ->setMaxDepth(2)
                                ->setSeparator(" : ").PHP_EOL;
                        ?>
                    </h3>
                </div>
                
                <!-- Conteúdo das Páginas-->
                <?php echo $this->layout()->content; ?>

                <div class="clearfix"></div>
            </div>

            <div class="clearfix"></div>

        </div>
        <div id="footer">
            <p>Vinhos Da Hora - Todos os direitos reservados</p></div>
    </body>
</html>