<table>
    <thead>
        <tr>
            <th>Pedido</th>
            <th>Data</th>
            <th>Cliente</th>
            <th>Valor</th>
            <th width="8%">Ação</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->pedidos as $pedido): ?>
            <tr>
                <td><?php echo $this->escape($pedido->getId()) ?></td>
                <td><?php echo $this->escape($pedido->getDataHora()) ?></td>
                <td><?php echo $this->escape($pedido->getCliente_id()->getNome()) ?></td>
                <td><?php echo Zend_Registry::get('currency')->toCurrency($this->escape($pedido->getValor())) ?></td>
                <td>
                    <a href="<?php echo $this->url(array('controller' => 'pedidos', 'action' => 'view', 'module' => 'admin', 'id' => $pedido->getId()), null, 1) ?>">
                        <img src="<?php echo $this->baseUrl("/images/icons/edit.png"); ?>" alt="Editar">
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php echo $this->paginationControl($this->pedidos, 'Sliding', 'paginator.phtml'); ?>