<h3>Meus Pedidos</h3>
<div class="content-line"></div>
<?php if (count($this->pedidos)): ?>

    <table>
        <thead>
            <tr>
                <th>Pedido</th>
                <th>Data e Hora</th>
                <th>Valor R$</th>
                <th>Tipo de Pagamento</th>
                <th>Status</th>
                <th>Ação</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->pedidos as $pedido): ?>
                <tr>
                    <td><?php echo $this->escape($pedido->getId()); ?></td>
                    <td><?php echo $this->escape($pedido->getDataHora()); ?></td>
                    <td><?php echo Zend_Registry::get('currency')->toCurrency($pedido->getValor()); ?></td>
                    <td><?php echo 'Não Definido' ?></td>
                    <td><?php echo 'Não Definido' ?></td>
                    <td><a href="<?php echo $this->url(array('controller' => 'meus-pedidos', 'action' => 'view', 'module' => 'site', 'id' => $pedido->getId())); ?>">detalhes</a></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    <center>Não existe pedidos para este usuário.</center>
<?php endif; ?>
