<h3>Detalhes do Pedido</h3>
<div class="content-line"></div>
<table>
    <tbody>
        <tr>
            <td><strong>Pedido:</strong></td>
            <td><?php echo $this->escape($this->itensPedidos[0]->getPedido_id()->getId()); ?></td>
        </tr>
        <tr>
            <td><strong>Data e Hora:</strong></td>
            <td><?php echo $this->escape($this->itensPedidos[0]->getPedido_id()->getDataHora()); ?></td>
        </tr>
        <tr>
            <td><strong>Valor R$:</strong></td>
            <td><?php echo Zend_Registry::get('currency')->toCurrency($this->itensPedidos[0]->getPedido_id()->getValor()); ?></td>
        </tr>
        <tr>
            <td><strong>Produtos:</strong></td>
            <td>
                <?php 
                foreach ($this->itensPedidos as $itemPedido) {
                    echo $itemPedido->getQuantidade()." - ".$itemPedido->getProduto_id()->getNome()." - ".$itemPedido->getProduto_id()->getPreco()."<br><br>";
                }
                ?>
            </td>
        </tr>
        <tr>
            <td><strong>Tipo de Pagamento:</strong></td>
            <td>
                <?php if ($this->itensPedidos[0]->getPedido_id()->getTipo_pagamento() == "BoletoBancario"
                        && $this->itensPedidos[0]->getPedido_id()->getStatus_pagamento() != "Autorizado"
                        && $this->itensPedidos[0]->getPedido_id()->getStatus_pagamento() != "Concluido"): ?>
                    <?php echo $this->escape($this->itensPedidos[0]->getPedido_id()->getTipo_pagamento()); ?>
                    &nbsp;
                    <a href="">(imprimir 2º via)</a>
                <?php elseif ($this->itensPedidos[0]->getPedido_id()->getTipo_pagamento() == "DebitoBancario"): ?>
                    <?php echo $this->escape($this->itensPedidos[0]->getPedido_id()->getTipo_pagamento()); ?>
                    &nbsp;
                    <a href="">(imprimir 2º via recibo)</a>
                <?php else: ?>
                    <?php echo $this->escape($this->itensPedidos[0]->getPedido_id()->getTipo_pagamento()); ?>
                <?php endif; ?>
            </td>
        </tr>
        <tr>
            <td><strong>Status</strong></td>
            <td>
                <?php if ($this->itensPedidos[0]->getPedido_id()->getStatus_pagamento() == "Concluido"
                        || $this->itensPedidos[0]->getPedido_id()->getStatus_pagamento() == "Autorizado"): ?>
                    <img src="<?php echo $this->baseUrl('images/confirmado.png'); ?>"/>&nbsp;Confirmado
                <?php else: ?>
                    <?php echo $this->escape($this->itensPedidos[0]->getPedido_id()->getStatus_pagamento()); ?>
                <?php endif; ?>
            </td>
        </tr>
    </tbody>
</table>
<br>
<a href="/meus-pedidos">Voltar</a>